### ISSUE TITLE
[内容错误] 方法名错误

### ISSUE THREAD

**Issue by Gnosnay** [kumakichi/easy_rust_chs#1]
> 下面再举一个例子:我们知道，如果unwrap不起作用，可以用unwrap_or方法给出一个值。之前我们写的是:let fourth = my_vec.get(3).unwrap_or_(&0);。

这里的方法名应该是`my_vec.get(3).unwrap_or(&0)`，感谢您的翻译

**Comment by kumakichi** [comment]
感谢反馈
